### ISSUE TITLE
teach linter about the $argv and $argc variables

### ISSUE THREAD

**Issue by divinity76** [eclipse-pdt/pdt#120]
$argv and $argc are global variables when php-cli is invoked, but the linter doesn't know about these 2 magic variables. 
as a workaround, cli scripts can currently do
```php
#!/usr/bin/env php
<?php
/** @var int $argc */
/** @var string[] $argv */
var_dump($argc, $argv);
```
and the linter won't complain, but would be nice if the linter had built-in support for these variables.

**Comment by flack** [comment]
I'm on version 8.1.0.202306111945 and I'm still seeing these warnings:

<img width="249" alt="screen" src="https://github.com/eclipse-pdt/pdt/assets/425166/e1293e55-20d8-4a3d-a5f2-e0d38e6a1668">

Did this regress somehow?

**Comment by zulus** [comment]
Could you run project -> clean?

**Comment by flack** [comment]
I tried, but didn't make a difference. I created a new file, typed `$argc`, and it immediately gets underlined as warning with the message "Variable '$argc' is undefined"

**Comment by zulus** [comment]
should be in upcoming build

**Comment by flack** [comment]
just updated, cleaned the project, created a new file and still get these:

<img width="209" alt="Bildschirmfoto 2023-07-04 um 23 01 59" src="https://github.com/eclipse-pdt/pdt/assets/425166/cf4730d7-2b45-423f-b188-9ff959e99566">

**Comment by zulus** [comment]
Its still old build (from 12), ill force publish

**Comment by flack** [comment]
Tested again and it's now validating correctly. No warning in global scope, warning in function scope: 

<img width="312" alt="Bildschirmfoto 2023-07-05 um 15 54 12" src="https://github.com/eclipse-pdt/pdt/assets/425166/3b5cb3cd-7803-4d03-a62e-242a35246930">

It's a bit weird that `$argc`/`$argv` are rendered like superglobals / language constructs now, even when they are just local variables in a function. But I can also make a separate ticket for that :-)

**Comment by zulus** [comment]
> It's a bit weird that `$argc`/`$argv` are rendered like superglobals / language constructs now, even when they are just local variables in a function. But I can also make a separate ticket for that :-)

Thanks!
