### ISSUE TITLE
Support `scalar` type in docblocks

### ISSUE THREAD

**Issue by clue** [eclipse-pdt/pdt#172]
**Is your feature request related to a problem? Please describe.**

At the moment, PDT complains about the `scalar` type in docblocks like `@param`/`@return`/`@var` complaining about "scalar cannot be resolved to a type". Other types work fine with no problem. The `scalar` type is widely supported by other tools such as phpDocumentor and PHPStan.

![Untitled3](https://github.com/eclipse-pdt/pdt/assets/776829/11787bcc-1b10-4760-bf60-3a1cd03a0b17)
See PHPStan playground as source: https://phpstan.org/r/a61337af-e21d-440f-9da0-17c8b50d3cc3

The `scalar` type isn't used often in practice afaict, in particular because PHP as a whole is transitioning to use more strict types. As of PHP 8+, it can be replaced with a union type of `string|int|float|bool`. Note that `scalar` is not a "real" type in the sense that it can not be used as a native type declaration in PHP.

**Is this feature require new UI elements or modify existing?**

No new UI elements required as far as I can tell.

**Describe the solution you'd like**

The `scalar` type should be supported in docblocks but not as a native PHP type.

**Describe alternatives you've considered**

The `scalar` type can be replaced with a union type of `string|int|float|bool`. This is easy enough to probably not affect most PDT users. That said, I wonder if it makes sense to adjust the code base to work around minor quirks in IDEs.

**Additional context**

Glad to see PDT is picking up some speed again lately, so I'm happy to support this development by sponsoring the excellent work done by @zulus ❤️ Most PDT quirks regarding latest PHP changes have been resolved for me recently, so while I realize this is probably not the most pressing feature, it's also one of the last occurrences that mark my code as red. Keep up the good work!

* https://github.com/clue/framework-x/blob/f7bf6ee136f03e4657dc89de600dbef4749c37da/src/Container.php#L13
* https://github.com/phpstan/phpstan/discussions/4507
* https://www.php.net/manual/en/function.is-scalar.php
* https://docs.phpdoc.org/3.0/guide/references/phpdoc/types.html

**Comment by mlocati** [comment]
I'm wondering how PDT would behave if a project uses a class named `scalar` ([which is absolutely legit](https://3v4l.org/EBmgM)).

**Comment by clue** [comment]
> I'm wondering how PDT would behave if a project uses a class named `scalar` ([which is absolutely legit](https://3v4l.org/EBmgM)).

Nice edge cause – though not specific to the `scalar` type.

It looks like the `@param integer` referencing the `int` type has preference over any `integer` class: https://3v4l.org/6C7Nl + https://phpstan.org/r/9afb97cc-81c8-4ad7-ab4b-f014e21a3171

Personally, I don't have a strong preference for either case, but other tools seem to ignore the class with the same name in this case. In either case, I don't think PDT has to "resolve" the type at all, merely not marking `scalar` as invalid would be *good enough* for me.

**Comment by zulus** [comment]
> I'm wondering how PDT would behave if a project uses a class named `scalar` ([which is absolutely legit](https://3v4l.org/EBmgM)).

Similar to string before it becomes typehint. If you use scalar in phpdoc it will be inferenced as phpdoc type, all other (or even Scalar in phpdoc) will be resolved as class.

**Comment by zulus** [comment]
> Glad to see PDT is picking up some speed again lately, so I'm happy to support this development by sponsoring the excellent work done by @zulus ❤️ 

Thank You! This helps me a lot, especially with my therapy ;)

> Most PDT quirks regarding latest PHP changes have been resolved for me recently, so while I realize this is probably not the most pressing feature, it's also one of the last occurrences that mark my code as red. Keep up the good work!

Easy TODO. Shouldn't prevent "scalar" class name. NOTE: scalar fake type will work only inside PHPDoc
