### ISSUE TITLE
.inc files do not open in PHP Editor

### ISSUE THREAD

**Issue by AntonVomFriedabach** [eclipse-pdt/pdt#237]
**Describe the bug**
* When opening a .inc file in my project, it opens with the TextEditor. 
* When I select "Open with" and select PHP Editor, I get a popup "Unsupported Content Type in Editor". The file opens in the PHP Editor, but there's no source code formatting (i.e. it's displayed in plain text).
* The error log reads:

Unexpected IDocument implementation: org.eclipse.core.internal.filebuffers.SynchronizableDocument
Unexpected IDocumentProvider implementation: org.eclipse.dltk.internal.ui.editor.SourceModuleDocumentProvider
StructuredTextEditor being used without StructuredDocument
Input Name: actions.inc <- The file I wanted to open

**Describe the eclipse environment**
Eclipse 2023-06
PDT 8.0
No plugins installed

**Describe your system**
 - OS: Windows 10
 - Version: 22H2 (latest updates)
 - PHP executable version of project: 8.2.5 (not sure if relevant here)
 - Utilis: no other utils used
eclipse.buildId=4.28.0.20230608-1200
java.version=17.0.7
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.php.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.php.product

**To Reproduce**
1. From your project, try to open .inc file
2. Observe it opens in Text Editor, not  PHP Editor
3. Try "Open With" and select "PHP Editor"
4. Observe message "Unsupported Content Type in Editor"

**Expected behavior**
.inc file should open in PHP Editor just like regular PHP files

**Screenshots**
Select open with:
![image](https://github.com/eclipse-pdt/pdt/assets/134985331/0b2be7ed-42d2-4c2c-a540-74bedbf2731f)
Error message:
![image](https://github.com/eclipse-pdt/pdt/assets/134985331/c0be1269-d2ca-493a-b1be-d3b26e431a1f)
File looks like this (it has proper <?php tags)
![image](https://github.com/eclipse-pdt/pdt/assets/134985331/683d31d6-1100-400a-ba63-b617a9b63968)
Content Types settings look like this (you can see the .module file association I've created myself, which works (see below) - .inc doesn't work even though listed and locked):
![image](https://github.com/eclipse-pdt/pdt/assets/134985331/91e31342-43aa-4f06-951a-e2cdbfe29f5d)

**Additional context**
Regular .php files open in PHP Editor as expected. I also have some .module files that are PHP files, for which I've selected "Use it for all .module files" in the "Open With" => PHP Editor dialog. They open in PHP Editor as expected, syntax highlighting working as expected.

**Comment by zulus** [comment]
Good catch! Looks like conflict with C++ extension from TM terminal (strange)

**Comment by zoide** [comment]
@zulus I've uninstalled TM terminal, but the problem still persists. It seems to be locked by C/C++ CDT itself?

**Comment by zulus** [comment]
> @zulus I've uninstalled TM terminal, but the problem still persists. It seems to be locked by C/C++ CDT itself?

TM Terminal is safe (fortunately)

I found dependency in remote project support (inside org.eclipse.ptp.remote feature). In recent snapshot PDT no longer install CDT core (tested on my env). You can update to latest snapshot or just drop "PTP PDT Synchronization Support UI"

**Comment by zulus** [comment]
PTP report: https://bugs.eclipse.org/bugs/show_bug.cgi?id=582165

**Comment by zoide** [comment]
Hi again. I still have this issue. I have installed latest nightly of PDT. But I do not have PTP (Parallel Tools Platform?) installed. 
Also, I do not see any "PTP PDT Synchronization Support UI" installed. 
I have C/C++ Development Tools installed. I can't get rid of those.

There must be some other component that also causes this issue.

Should I post a list of my installed components?

Thanks.
