### ISSUE TITLE
Eclipse PDT freezes on debugger tooltip window

### ISSUE THREAD

**Issue by older777** [eclipse-pdt/pdt#238]
**Describe the bug**
Eclipse freezes for long time at tooltip shown in next example (nested arrays generator)
[test.php.tar.gz](https://github.com/eclipse-pdt/pdt/files/11823708/test.php.tar.gz)

**Describe the eclipse environment**
Version: 2023-06 (4.28.0)
Build id: 20230608-1333

**Describe your system**
 - OS: Linux Mint
 - Version 21.1
 - PHP Version 7.4
 - XDebug 

**To Reproduce**
1. set XDebug breakpoint at row 31
2. run code and navigate mouse on $item after break
3. something wrong with nested array set in tooltip, it freezes for 1-2 minutes

**Expected behavior**
No freezes

**Screenshots**
![image](https://github.com/eclipse-pdt/pdt/assets/58441394/2a56801c-dc2d-4bdb-8666-d3a96ba0f1ad)

**Comment by older777** [comment]
Hi, sorry for worries.
I tried other oldest Linux Mint (20.1, 5.15-0-67-generic) - works ok, no freezes.
Looks like there's some issue in my Linux(21.1, 5.19.0-45-generic) 🤦

**Comment by older777** [comment]
In additional of my case.
I just re-create my workspace, .metadata moved to .metadata, reconfigured Eclipse PDT after.
I think there's plugin(s) issue in .meradata
Now it works good.
![image](https://github.com/eclipse-pdt/pdt/assets/58441394/780eec52-a728-4ea0-88eb-3dd1cbeef8ea)

**Comment by zulus** [comment]
Could you please enable UI free monitoring (Preferences -> UI Free Monitoring and enable both checkboxes) and later upload logs from Window -> Show View -> Other -> Error Log?

**Comment by older777** [comment]
I can share old .log file [log.old.tar.gz](https://github.com/eclipse-pdt/pdt/files/11893583/log.old.tar.gz)
also here is of screenshot of .metadata/.plugins list (left part is old, right is new .metadata) for the difference 
![image](https://github.com/eclipse-pdt/pdt/assets/58441394/bf499add-b9ea-40ec-b819-0b4309fbe533)

version.ini (old and new, is same)
#Wed Jun 28 10:58:59 MSK 2023
org.eclipse.core.runtime=2
org.eclipse.platform=4.28.0.v20230605-0440
