### ISSUE TITLE
Dead URL for update site in 8.0.0 release notes 

### ISSUE THREAD

**Issue by olberger** [eclipse-pdt/pdt#239]
Just a minor error I've seen in the [8.0.0 Release description](https://github.com/eclipse-pdt/pdt/releases/tag/R8_0_0), where it reads `Update Site: https://download.eclipse.org/tools/pdt/updates/8.2`, which 404 for me.

Hth,

**Comment by mlocati** [comment]
Yep, I think it should be `https://download.eclipse.org/tools/pdt/updates/8.0` (or `https://download.eclipse.org/tools/pdt/updates/latest`)

**Comment by zulus** [comment]
TX! Fixed
