### ISSUE TITLE
PDT doesn't correctly parse `Symfony\Component\Console\Application` 6.3

### ISSUE THREAD

**Issue by flack** [eclipse-pdt/pdt#243]
**Describe the bug**

`Symfony\Component\Console\Application` in version 6.3 has 49 methods:

https://github.com/symfony/symfony/blob/v6.3.0/src/Symfony/Component/Console/Application.php

However, in the PDT outline, only 7 methods are shown:

<img width="426" alt="outline" src="https://github.com/eclipse-pdt/pdt/assets/425166/f1ddc8ab-42d2-479b-aa01-540dc2089d1d">

That also has the effect that when you extend this `Application` likes this:

```php
class testapp extends Symfony\Component\Console\Application
{
}
```

PDT displays the following error:
`The type testapp must implement the inherited abstract method ResetInterface::reset()` 
(because `reset` is one of the methods in the baseclass it doesn't see)

**Describe the eclipse environment**
- Eclipse 2023-06 
- PDT 8.1.0.202306111945

**Describe your system**
 -  macOS 12.6

**To Reproduce**
see above

**Expected behavior**
PDT should be able to parse all valid PHP files

**Comment by zulus** [comment]
Good catch! Fix will be available in upcoming build

**Comment by flack** [comment]
I just updated and cleaned the project, it's recognizing the functions now, but somehow it thinks they don't belong to the class:

<img width="487" alt="Bildschirmfoto 2023-07-04 um 22 53 36" src="https://github.com/eclipse-pdt/pdt/assets/425166/fae407a7-a9dc-490f-a724-be2232b0c6c4">

the error when extending the class about the missing `reset` implementation is still shown:

<img width="520" alt="Bildschirmfoto 2023-07-04 um 22 55 35" src="https://github.com/eclipse-pdt/pdt/assets/425166/5e9598e0-811a-48dd-917a-57ab5159be0a">

**Comment by zulus** [comment]
I pushed extra patch. Now have to be ok :P I tested with recent 6.3, build will be available after couple minutes

**Comment by flack** [comment]
just tested again, looks great now, thx!
