### ISSUE TITLE
Confusion when importing a class used as attribute argument

### ISSUE THREAD

**Issue by pounard** [eclipse-pdt/pdt#244]
Consider the following code:

```php
<?php

declare(strict_types=1);

namespace Foo\Domain\ClientSecurity\Query;

use Foo\Domain\Client\Model\SalarieId;
use Foo\Shared\Attr\Repository;
use Foo\Shared\Query\ListQuery

#[Repository(Profil::class)] // HERE IS LACKING THE USE STATEMENT
class ProfilQuery extends ListQuery
{
}
```

When I hit CTRL+SHIFT+o (re-organise imports), it converts it to:

```php
<?php

declare(strict_types=1);

namespace Foo\Domain\ClientSecurity\Query;

use Foo\Domain\Client\Model\SalarieId;
use Foo\Shared\Attr\Repository;
use Foo\Shared\Attr\Repository as Profil; // PLEASE NOTE HERE THE "as Profil"
use Foo\Shared\Query\ListQuery

#[Repository(Profil::class)]
class ProfilQuery extends ListQuery
{
}
```

The `Foo\Shared\Attr\Repository as Profil` `use` statement is wrong and should be, in my case, `Foo\Domain\ClientSecurity\Model\Profil` instead.

I should get:

```php
<?php

declare(strict_types=1);

namespace Foo\Domain\ClientSecurity\Query;

use Foo\Domain\Client\Model\SalarieId;
use Foo\Domain\ClientSecurity\Model\Profil;
use Foo\Shared\Attr\Repository;
use Foo\Shared\Query\ListQuery

#[Repository(Profil::class)]
class ProfilQuery extends ListQuery
{
}
```

Worst part is that once I fixed it manually, if I hit CTRL+SHIFT+o again, it will revert back my fix to the broken one.

It's been a few weeks I'm experiencing this behavior, I was waiting for it to be naturally fixed because a lot of people are writing bugs now.

I'm reproducing it right now with the 8.1.0.202307031117 build.

**Comment by zulus** [comment]
Fixed

BTW you have syntax error inside `use Foo\Shared\Query\ListQuery` line, missing semicolon ;)

**Comment by pounard** [comment]
> BTW you have syntax error inside use Foo\Shared\Query\ListQuery line, missing semicolon ;)

Yes, because this is part of a client project, I had to manually change a few things when pasting to anonymize client name and project destination. Anyway, thank you very much !
