### ISSUE TITLE
New search icon

### ISSUE THREAD

**Issue by konrad-krzak** [eclipse-pdt/pdt#253]
**Is your feature request related to a problem? Please describe.**
The search icon is unintuitive.

**Is this feature require new UI elements or modify existing?**
New search icon (search.svg)

**Describe the solution you'd like**
Changing the search icon.

**Describe alternatives you've considered**
Changing of all icons in eclipse ui.

**Comment by zulus** [comment]
This should be reported on eclipse.platform.ui : https://github.com/eclipse-platform/eclipse.platform.ui
