### ISSUE TITLE
not detecting method implemented in parent class

### ISSUE THREAD

**Issue by aln-1** [eclipse-pdt/pdt#255]
php 8.2

interface SomeInterface {
  abstract public function someFunction ();
}

abstract class Parent implements SomeInterface
{
  public function someFunction () {
  }
}

class Child extends Parent
{
}

Eclipse will flag the "Child" class with errors and will recommend to implement the "someFunction" method or to make the class abstract. Which is of course wrong.

**Comment by pounard** [comment]
It happens sometime when code isn't inside the build path / include path.

**Comment by zulus** [comment]
Strange. Which PDT version you use? On recent snapshot I see only error for "Parent" keyword, could be also for "abstract" but this is another case

**Comment by aln-1** [comment]
yes, wrong choice of names in my example . of course "parent" is a reserved word. 
I'm using pdt plugin version 8.0.0.202306041617.
My real life example is a laravel Model implementation. Eclipse complains that the "ArrayAccess" methods are not implemented but in fact they are implemented in the laravel model base class.

**Comment by aln-1** [comment]
<img width="778" alt="Screenshot 2023-10-11 at 14 47 59" src="https://github.com/eclipse-pdt/pdt/assets/17613001/08e6c93c-2255-4c9b-a2cc-73fee7dae30f">

**Comment by zulus** [comment]
Latest stable is 8.1, current snapshot 8.2, I cannot reproduce here

**Comment by aln-1** [comment]
it is indeed solved with 8.1
