### ISSUE TITLE
Quick outline is not appearing

### ISSUE THREAD

**Issue by zucha** [eclipse-pdt/pdt#276]
**Describe the bug**
Quick outline is not appearing (ctrl+o).

**Describe the eclipse environment**
clipse IDE for PHP Developers (includes Incubating components)

Version: 2024-03 (4.31.0)
Build id: 20240307-1437

**Describe your system**
5.15.0-107-generic #117~20.04.1-Ubuntu SMP Tue Apr 30 10:35:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
PHP 8.3.6 (cli) (built: Apr 11 2024 20:23:19) (NTS)

**To Reproduce**
php editor
ctrl+o

**Expected behavior**
Small window with class methods and properties.

**Additional context**
Tryed to clean projects, remove index files. No results. 
Autocomplete works well.

**Comment by zulus** [comment]
I fixed this today on DLTK, you need: https://download.eclipse.org/technology/dltk/updates-dev/latest-nightly/

Will be released soon together with 2024-06

**Comment by zucha** [comment]
Nice work! Thanks!
