### ISSUE TITLE
Short arrow closure syntax gives warnings with function args

### ISSUE THREAD

**Issue by pounard** [eclipse-pdt/pdt#73]
Hello ! Since 2020-03 and then still present in 2020-06 when I write a closure using short arrow syntax (PHP >= 7.4), closure arguments raise a `Variable {$foo} is undefined` warning.

Version is:
```
Eclipse IDE for PHP Developers (includes Incubating components)
Version: 2020-06 (4.16.0)
Build id: 20200615-1200
```

I have quite a few addons installed, but I noticed the bug prior to installing it.

 - OS: Running ArchLinux, uname output: `Linux guinevere 5.7.6-arch1-1 #1 SMP PREEMPT Thu, 25 Jun 2020 00:14:47 +0000 x86_64 GNU/Linux`

1. Open a PHP file,
2. Write a short arrow syntax closure with at least one argument.

A few screenshots following.

![20200703-EclipsePDTWarningInSASC-1](https://user-images.githubusercontent.com/341855/86441420-7b0e1880-bd0c-11ea-8a0a-49a3111fb97c.png)

![20200703-EclipsePDTWarningInSASC-2](https://user-images.githubusercontent.com/341855/86441424-7cd7dc00-bd0c-11ea-9cf3-d43a232f2cf2.png)

OK that's not really visible, but notice the yellow underline on the closure parameter name, then at its usage.

**Comment by quazardous** [comment]
Hi,

I'm having this warning too Eclipse PDT 8.0.0.202007171531 (@fedora 34)

**Comment by lpotherat** [comment]
Hi, 
Bug always present in     PHP Development Tools (PDT)	8.0.0.202112011911

**Comment by pounard** [comment]
I updated this morning, I'm now running version 8.1.0.202306071122 and I'm still experiencing this bug.

**Comment by zulus** [comment]
@pounard Can you post example code?

**Comment by pounard** [comment]
First one found in my currently opened project (sorry it's french domain code):

```php
    /**
     * Récupère le ou les destinataires des contacts entreprise de la demande.
     *
     * @return Destinataire[]
     */
    public function getEntrepriseDestinataireAll(): array
    {
        return \array_filter(
            \array_map(
                fn (Contact $contact) => $contact->email ? new Destinataire((string) $contact->id, $contact->email) : null,
                $this->getEntrepriseContactAll()
            )
        );
    }
```

Here the `$contact` variable inside the closure body is yellow underlined with the following message on hover:

> Variable '$contact' is undefined

**Comment by pounard** [comment]
Forgot to mention: PHP validation for this project is configured to PHP 8.0, fun fact, when switching to PHP 8.2, I don't have warnings in most case, except this one, see:

![Capture d’écran du 2023-06-09 12-13-46](https://github.com/eclipse-pdt/pdt/assets/341855/73602cc6-7cf2-41bb-b77c-cd95deb28ccf)

Now, only the part in `new Destinataire((string) $contact->id, $contact->email` is underlined as being an error, the rest is fine.

So there are two bugs here:

- first, it works with PHP 8.2 parser, but not previous ones (although I didn't tested using PHP 8.1, this project is kind huge to validate),
- now that it works in 90% percent of use cases, there are still some pitfalls in 8.2 parser.

**Comment by pounard** [comment]
> Can you prepare?

I'm sure to understand the question here ?
